export default {
  click_rate: "点击数/展示数",
  cpc: "总花费/点击数",
  cpm: "总花费*1000/展示数",
  convert_cost: "总花费/转化数",
  convert_rate: "转化数/点击数",
  active: "通过转化工具箱回传的激活数",
  active_cost: "总花费/激活数",
  active_rate: "激活数/点击数",
  register_cost: "总花费/注册数",
  register_rate: "注册数/点击数",
  // 关键行为数: "有APP内关键行为的用户数量",
  // 关键行为率: "关键行为数/激活数",
  pay_count: "通过转化工具箱回传的付费数",
  pay_count_cost: "总花费/付费数",
  pay_count_rate: "付费用户数/点击数",
  self_real_consumption: "广告花费/（1+媒体返点）",
  self_customer_register: "所选时间范围内，首次安装应用并打开的排重设备数",
  self_active_cost: "实际花费/激活数",
  self_registers: "所选时间范围内，注册事件的排重设备数",
  self_register_cost: "实际花费/注册数",
  self_user_new_pay: "所选时间范围内，当日激活且当日付费的设备总数",
  self_user_new_pay_rate: "新增付费数/激活数",
  self_income_new_user: "所选时间范围内，当日激活且当日付费的付费金额",
  self_ltv1: "选择日期范围内的新增设备，在当日的平均付费收入",
  self_roi1: "选择日期范围内的新增设备，在当日的付费收入/实际花费 ",
  self_monetization_clicks: "所选时间范围内，激活用户的变现广告点击总数",
  self_average_monetization_clicks:
    "所选时间范围内，激活用户的人均广告点击次数。计算公式：变现点击数/激活数"
};
