export default {
  PROMOTED_OBJECT_TYPE_LINK: "网页",
  PROMOTED_OBJECT_TYPE_LINK_WECHAT: "网页（微信推广）",
  PROMOTED_OBJECT_TYPE_ECOMMERCE: "电商推广",
  PROMOTED_OBJECT_TYPE_APP_ANDROID: "Android应用",
  PROMOTED_OBJECT_TYPE_APP_IOS: "IOS应用",
  PROMOTED_OBJECT_TYPE_APP_ANDROID_MYAPP: "应用宝推广",
  PROMOTED_OBJECT_TYPE_APP_ANDROID_UNION: "Android应用（联盟推广）",
  PROMOTED_OBJECT_TYPE_LOCAL_ADS_WECHAT: "本地广告（微信推广）",
  PROMOTED_OBJECT_TYPE_QQ_BROWSER_MINI_PROGRAM: "QQ 浏览器小程序",
  PROMOTED_OBJECT_TYPE_QQ_MESSAGE: "QQ 消息",
  PROMOTED_OBJECT_TYPE_LEAD_AD: "销售线索"
};
